name: 'Chromatic'
on: push
jobs:
    chromatic-deployment:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: corepack enable
            - uses: actions/setup-node@v3
              with:
                  node-version-file: .node-version
                  cache: pnpm
            - run: pnpm install
            - uses: chromaui/action@v1
              with:
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
